### PR TITLE
Added build configuration for x64

### PR DESCRIPTION
**Pull request by paulthomson**
Some projects require x64 builds. No harm in having this. Hopefully it is not chosen as the default though.

### CODE REVIEW

**Comment by paulthomson** [comment]
The diff is looking larger than it should. Is this because of line endings?

**Comment by pdeligia** [comment]
Now that we have the .gittattribute for line ending normalization (see af9975d6d5ba23c5367af590e8b7d04de1d9a602), is this safe to merge? Just let me know when we should and I can go ahead with merging!

**Comment by paulthomson** [comment]
I've fixed it now by rewriting my pushed branch (just for some git practice), for which I received many warnings telling me not to do it! :-) So you should see the diff looks OK now (on github) and so you can now merge this, if you want!

**Comment by pdeligia** [comment]
Oh, I found a small "bug" in the commit which we should probably get fixed before merging. Basically, the normal output directories are something like this:

`<OutputPath>..\..\Binaries\Release\</OutputPath>` (changes depending on the nesting of the directory, so its not the same for all projects)

But the new x64 build configuration is using the default:

`<OutputPath>bin\x64\Release\</OutputPath>`

I think the rest of the properties are as they should, which is good, but we should double check.

**Comment by paulthomson** [comment]
OK, I think I've fixed that but please check as it was a bit error-prone!

**Comment by pdeligia** [comment]
Thanks, looks good!

**Pull request merged**
