### PR TITLE
MachineId hash comparison changes

### PR DESCRIPTION
**Pull request by chandramouleswaran**
Changes for machine ID hash comparison.

### CODE REVIEW

**Comment by akashlal** [comment]
@chandramouleswaran, so far our design has used MachineId.Name only for logging purposes. It has no semantic effect. With your changes the Name captures the MachineId itself. Thus, a user can actually end up creating the same MachineId by using the same FriendlyName. Is this something you want? Or do you just want to control the log?

**Comment by chandramouleswaran** [comment]
Yes. We want the ability to create MachineId using friendly name.

**Comment by akashlal** [comment]
Thanks. Let me make two observations. 

First, the current change will break existing clients. (And there is a reason why no unit test covers this breaking change.) The friendly name has been used so far for logging purposes, not for indexing MachineId. Existing code will fail when two IDs with the same friendly name are created. Second, we try to follow the principle "what you test is what you execute". This is the reason why we have much fewer tests against the production runtime. Two MachineIDs created with same friendlyName will give two different IDs in bug-finding, but the same one in production. 

Let me make an alternative proposal. We add the following API to PSharpRuntime: CreateMachineIdFromString. The BugFindingRuntime will hash the string and still use Value for uniqueness. The ProductionRuntime will create a new string field in MachineId for uniqueness (thus, it is possible that some MachineIds use Value, and some use the string, but that is fine). This way we guarantee there is no change in semantics from test to production; also that friendlyName will remain a logging help only.

Does this sound useful?

**Comment by chandramouleswaran** [comment]
Akash working on a releasing the package with string machine ID.

**Pull request closed without merging**
