### PR TITLE
Resolve #234: Change "this.Goto(typeof(T));" to "this.Goto<T>();" wit…

### LINKED ISSUE #234: Goto<T> instead of Goto(typeof(T))
where `T : MachineState`. Request from Chandra.

### PR DESCRIPTION
**Pull request by TedHartMS**
…h " where T: MachineState" (or MonitorState)

### CODE REVIEW

**Comment by pdeligia** [comment]
@TedHartMS @akashlal I don't think that we should remove the old version, this will break compatibility with existing code (both ours and our users). We could just add the new version alongside the current method. By the way, I do not fully understand the reasoning behind this request. Is this just a syntactic preference? Or there is some stronger reason behind? Is this because they do not have access to `typeof()`? But in either case, I would keep both. Any thoughts?

@Ted: assuming we all agree on the above, could you please make this change (which should hopefully simplify the commit too) and rebase so I can check it again?

**Comment by TedHartMS** [comment]
Agreed--will make the change.

`typeof()` is always available. `Goto<T>()` will error at compile time if T is not a `MachineState` (or `MonitorState`).

**Comment by TedHartMS** [comment]
Restored as deprecated in #ee013c7. This will require disabling warning 618 if warnings are treated as errors.

`PSharpRuntime` has several methods that take `(Type type, ...)`:
* the `CreateMachine` variants
* `RegisterMonitor`
* `InvokeMonitor` This is the only one that also has a generic overload: `InvokeMonitor<T>(Event e)`.
* also INetworkProvider.RemoteCreateMachine

For consistency should we add the generic form for these? Deprecate the non-generic form?

**Comment by pdeligia** [comment]
What you just said would be great Ted, please feel free to open an issue and work on it on a separate branch. But maybe put it as a low priority item in your TODO list, since no one asked for it directly (yet)?

**Pull request merged**
