### PR TITLE
Added On* structured logging methods to ILogger; added StateMachineLo…

### PR DESCRIPTION
**Pull request by TedHartMS**
…gger implementation

### CODE REVIEW

**Comment by akashlal** [comment]
All this is great! Only thing that I'll bring out to notice is that `MachineMap` got added to `PSharpRuntime` (which is fine) and `GetTargetMachine` calls `OnSend` (which is not ideal, but I can live with it).

**Comment by TedHartMS** [comment]
Thanks. Moving MachineMap into PSharpRuntime and adding GetTargetMachine centralized 4 repeated code blocks. No new logging calls have been added; where GetTargetMachine calls OnSend, it was already calling base.Log("<SendLog>...").

**Comment by pdeligia** [comment]
The changes look great to me (thanks Ted!), however when running the tests all messages are now always logged to console. I am trying to find out what has changed causing this behaviour.

**Comment by pdeligia** [comment]
There is also another bug: when running `PSharpTester.exe` without verbosity (no `/v:N` given), and a bug is found, then the error log (e.g. `Raft.PSharpLibrary_0_3.txt`) contains no logged messages from the runtime (only user messages).

**Comment by pdeligia** [comment]
Btw, I pushed some minor changes (which I will rebase before merging), but we need to fix the above 2 bugs (might be 1 bug causing both issues) before merging. I will try to investigate more and see if I can fix it (hopefully will find some time today).

**Comment by pdeligia** [comment]
OK, I think I found what was going on in the case of the first bug. The `ConsoleLogger` always logs (minimum verbosity is set to 0 on the constructor). This was used inside the runtime as the default logger. I fixed the first bug by changing the default logger of the runtime to the `StateMachineLogger` which does not set to minimum verbosity to 0 by default. In production, logging should only happen if the user explicitly sets verbosity. Now to see why the logs are discarded from the `PSharpTester` ...

**Comment by pdeligia** [comment]
Actually, I am thinking to make a small change to the design. I am thinking that `StateMachineLogger` should just be an abstract class (which exists only to provide the default implementation for all the runtime-related logging, if someone doesn't want to implement that). We already provide basic implementations of it such as `ConsoleLogger` and `InMemoryLogger` (which is used by the tester). Also, the `ConsoleLogger` should not always log (only if verbosity is set), to keep it as it was before. If the user wants to implement their own logger, they can either subclass the abstract `StateMachineLogger` or implement `ILogger`.

**Comment by pdeligia** [comment]
Ok the minor re-design is done, and also fixed the 2nd bug.

The bug was that `base.Logger.LoggingVerbosity = 0;` was set in the constructor of the `BugFindingRuntime`, however, the testing engine could install (after the runtime is created) the `InMemoryLogger`, which was using the default verbosity of 2. I fixed it by always initializing the `InMemoryLogger` with default verbosity of 0 (since during testing we want to log all events in memory).

I will do some more testing, then merge.

**Pull request merged**
